---
title: "Analysis Notebook"
author: "Tyler Hoecker"
date: "9/21/2018"
output: html_document
---

### 9/21/18:  
Working through the procedure to go from the raw ouput of the data loggers to an R format. Have it streamlined so that columns, headers, etc. do not need to be changed. 
Issue emerged dealing with missing data, where if batteries dies (versus cable getting unplugged), those rows do not appear in data set. So, when plotting, they don't appear as missing, and the plot just connects a straight line between the dates. Ultimately I want to remove missing dates, but I want to be able to track those dates in R. So I had to manually add the dates where values are missing to: MPF, BHF

Should add an elevation column to dataframe so can plot by that instead of 'site'

### 9/24/18:  
- Made changes to the import function in 'read_soil_data' after changing the site names to Fire1-Fire2_Aspect, instead of FFA. Took a while to figure out the grep, but it works for now. 
- Worked on seedling allometry data. I think this will work! They have a pretty clean relationship, r  = 0.86 using the model from ecophysiology ( log[basa^2] + log[height] ). Made scatter plots to show Monica. 
- Put everything into an RMarkdown, which I will use to show Monica the progress.
- Plotting seedling counts, not tracking individuals, over time.

### 9/26/18:  
- Met with Monica, good meeting. Her suggestions:
    - switch axes to biomass~height/basal
    - plot temp data over top of seed survival to see if events line up with drops in seedlings
    - Order of operations for analysis: 1. Germination 2. Survival 3. Variation in biomass
    
### 10/3/18:
Revisited rose plots of wind data for Nate.

### 10/4/18:
Starting to work on incorporating weather data. Learned that read_excel is much faster if you can avoid producing warnings... so came up with a slightly better way to read in the data. The funtioncs in "read_soil_data.R" and "read_atmos_data.R" work very similarly, pretty quick given how much data are read. They import with read_excel, pick out columns and name them (this part is NOT GENERAL), and make sure they are classed properly. 
Does it make sense to make ATMOS data VERY long? I.E., should the column be 'varibale' and 'value'?

### 10/10/18
+ Putting weather + seedling work into RMarkdown
+ Making manual edits to seedling data based on notes.... Ok that is not really going to be feasible. Changed one set that was clear. Will have to rely on averages by aspect. 
+ Changed Buffalo north and south sites manually, to make Excel cells NOT a formula. Not sure why this is... but interferes with reading in NAs.
+ Looking at differences between air temperature and soil temperature

### 10/24/18
+ Went through and fixed any discrepencies in tag numbers. Does not include October visit to Maple and Buffalo, which have not been uploaded yet due to issue with Kobo.
+ Went through and looked at all of the dates that cells with heights recorded were sampled. Found some mis-labeled frameIDs, but could not detect any mistakes in the cell IDs. The cells that I found earlier that were measured only once or twice must then have been the result of a wrong frame ID, not a wrong cell ID. 
+ Got the data uploaded! Yay! Wow that was stressful. Then accidentally re-wrote the running_update file, so I had to re-do a bunch of the fixes that I made. 
+ Adding Buffalo-South manually (because we didn't do it in the field because we didn't know the frameIDs...)
+ Saved a season-end version of the data as "seedling_data_complete.csv" in the GitHub folder
+ Filled in: {2018-07-30	berry_huck	flat	pico	nw	95 E_2} because it was there for weeks, was missing one week, and then back. Must have been missed. Used numbers from previous week (24, 100)
+ Changed: {2018-08-11	berry_glade	south	pico	sw	35 6_C} to -999/DEAD because it was "dead" the week before and after
+ Deleted {2018-07-03	berry_glade	north	pmse	sw	1224 5_B} because the values were crazy and not consisten with other weeks.
+ Deleted {2018-07-31	berry_glade	north	pmse	ne	1789 6_B} because it didn't have a height, or other weeks, only basal one week.
+ Moved {2018-07-31	berry_glade	north	pmse	center	1267 4_B} to {5_B}
+ Estimated basal for {2018-07-31	berry_glade	north	pmse	center	1267 6_C}, 81, same as week before, had height, was missing basal.


### 10/25/18
+ Started making changes in GitHub/running_update instead of 'complete', but when I went make to complete, the ones I had just moved to line up didn't make sense anymore... The method I am using now is better, where it is sorted down to frame and the dates are successive rows, it is clear where they are missing and relatively easy to move them. I am changing too many to list but only when they are very obvious and w/o conflicts in new cells. 
+ All changes from yesterday are not being used...
+ Estimated:
    + {7/17/18	berry_glade	flat	pico	ne	1434 5_B} one missing week, made it average of weeks on either side.
    + 1355	7/31/18	berry_glade	north	pico	center	1355 9_A} one missing week, made it average of weeks on either side.
    + A few others estimated by interpolaton...
+ I think the data are good now. Pretty thorough multiple checks through and no gaps left. Caught a few dozen issues, not all are recorded here, but only made very obvious changes.
+ Plots look good, no more spurious increases.

### 10/26/18
+ Progress on GCC talk... going to work on plotting number of seedlings as a function of previous two weeks temperature.


## Key Points GCC talk:
+ All aspects show declines over the summer
+ South facing aspects are almost always the lowest, and north facing almost always the highest
    + Effect is magnified with more seedlings (if low, aspect less important)
+ Declines are concurrent with soil moisture
    + Summer minimal determines rates, no chance to recover with later moisture, further declines even after fall rains
  
### 11/08/18
+ Lots of messing around the last day until 10AM today trying to figure out issues with from frameIDs etc. They are solved! Totals add up correctly when figured many different ways. Built tibble that shows for each individual cell whether it germinated or not. 
+ Now I need to tie these data to the environmental data, and that will be the basis for the mixed-effects logistic regression. 
+ First step is the MELR for germination, then for survival, then add complexity.

### 11/12/18
+ Been working on logistic regression of germination and survival as a function of the environmental parameters. Using glm and glmer with family = binomial in both. The mixed effects (-er) does not seem to be adding information at this point. The germination model has significant terms, the survival model does not, except species. Need some help to interpret these results, not convinced. Bar plots suggest effects are similar for both survival and germination.

### 12/13/18
+ Sitting back down to this... Converting things to proportions; making dataframes by frame, site, aspect, and calculating means/st. devs for those. Double-checking that survival is proprotion of germinated. Calculated proportions as:

- Germination: 1 for every cell (in every frame) for every measurement period where there is a value. Germination = max(), so if there is a 1 at any point during the summer, the cell gets a 1 for germinated. Summarized, so no duplicated dates. Single value (0,1) per cell. Then, per frame (fire, aspect, frameID), total count of unique cells divided by 50 (total possible).
- Final measurement/ "established": 1 for every cell that has a value when we sampled in October, it would also have to have germinated. Then, per frame, total count of cells. Could calculate from germination proportion * survival proportion.
- Survival: Per site (fire, aspect), total count at final measurement divided by germination count.

+ Looking at histograms of distributions. The are skewed. Using arcsine-sqroot transform per Tony's stats manual. Seems acceptible, but still many zeros.

### 12/14/18
+ Adding error bars to bar plots. These are looking finalized, for the general patterns by site and aspect. Now to move on to modeling. Will put progress in 'Research_Update_2018_12_17.Rmd'

### 1/17/19
+ Some streamlining of data prep process so that it happens in independent scripts
+ Much considering of empirical cumulative distribution function. Plotting ecdf's for all sites does reveal some separation. For soil moisture, sites appear most distinct at 50th percentile. Less variability among sites in soil temperature, biggest separation is at 75th percentile or above. What is the best way to decide which percentile to us?
+ Calculatd VPD. Ends up being very easy from ATMOS, because Ea (atmospheric pressure) and RH (relative humiidity) are already given. So, Es = Ea/RH and VPD = Es - Ea. See ATMOS manual and Buck 1981. 
+ The problem with the met data is that we lose 1/3 of the sites... so there is already a lack of data because we only have 1 set of measurements per site, and then we reduce the information further. 

### 1/18/19
+ Was calculating VPD wrong! Was using atmospheric pressure as if it were atm vapor pressure... its not! 
+ So, even though the ATMOS calculates Es to calculate RH, it doesn't save it. The device can be set to record Ea instead of RH, but I didn't do that. Wouldn't save the step of calculating Es anyway. 

### 1/23/19
+ Finalized VPD calculation, it's correct now, based on info from ATMOS. Had to calculate ES using air temp, derive EA from RH and subtract. 
+ Spent some time this week also looking at GLMM. I think this is the right direction, but there are many ways to parameterize the model, so not sure what's correct.
+ Today I have been calculating geographic position indices (aspect, slope, TPI, TRI) to include in the model. There may be effects that are not accounted for by soil moisture / env. data we collected.
+ Saved that information as: dem_indices.csv in GitHub/seed-addition/data folder.
+ Still messing with glmer... I think I have a good model here, but is it right???

### 1/25/19
+ Will try to make a glmm for germination and put together a summary of germination and survival models before trying to work with a known-fate model per JPs suggestion.
+ These models are not really making sense... I think summarizing the information at the site-level is a major constraint. Even though there is variation in the counts, there is very limited variation in the abiotic data from which to model the counts. 

### 1/29/19
+ Been working through GLMMs the last few days, using resources from Robbie. 
+ Also plotted linear relationships for every predictor, which is helpful. Based on them we should be able to fit a model. 
+ Trying various diagnostics from the lectures Robbie gave me. Things still seem a bit funny... but not horrible. 
+ The coeffectients, though, don't necesarily jive with expectations. Topographic roughness is best predictor...
+ Re-scaling predictors removes an error from glmer about scales, but doesn't change results.
+ Questions that have emerged:
    - Should species be modeled separately or included as a model term? I'm leaning toward the latter.
    - How do I interpret correlation between the intercept and among fixed effects?
    - Which optimizer should I use?
    - Should I use fire and aspect as random effects? Or fire and site ("singular fit") or just site?
    - Why does R2 improve in models that include non-significant terms?
    - What does the warning of "singular fit" indicate? My sense is not enough information to estimate effects
    - Should I use a negative binomial or a poisson (log) link family?
    - Should I use the zero-inflated version. Things become insignificant... doesn't that mean less anti-consevative?

### 1/30/19 

I think I have a model that makes sense and is good:
```{r}
m <- glmer(count ~ species*(temp_max + mois_q75 + dev_north + tri) + (1|fire) + (1|fire:aspect), #species + 
           family = poisson(link = 'log'), 
           data = model_df,
           control=glmerControl(optimizer="bobyqa"))
```
+ This gives random effects for aspect nested in fire and for fire alone
+ 
+ Comparing partial R2s between models with and without generic landscape position metrics (TRI and dev. from N), suggests that measured variable (temp_max and mois) explain ~50% of variability, models that include position metrics explain ~70%. 

+ I should try to fit a model that uses all timepoints: glmer(count ~ previous two weeks abiotic). Using a random effect for frameID will account for the correlation in repeated measures, in addition to random effects for site.
    


### Week of 2/04
Good progress on the models.   
- Decision was made with MGT to not include DEM-derived metrics in the same model as measured metrics. So that simplified model selection.   
- Coded and effecient routine for estimating many models from a list of formulas, and choosing the top one based on AIC.  
- Realized potentially significant issue with soil moisture values: Maple are systemically higher. This means either the Maple measurements are off, or all of the others are. Investigated, found that the soil sensor should be calibrated before use... so I think it is related to soil texture or chemistry. Excluding Maple from the models, or bluntly subtrating 0.1 from all of the values, greatly improve model fit. 
- Estimated separate model using DEM-derived variables. This model is just as good. It is disappoinitng in a way, but could be an interesting route to go esp. for management focus, makes a predictive map based on DEM potentially useful. 
- Also summarized the dataset into two-week intervals, with all of the same metrics within the previous two weeks. Now I just need to try estimating a model from those data, that accounts for repeated measures. 

### Questions / Points for meeting with Winslow and Monica on 2/18:
- Review ANOVA results, figures
    - Is survival an interesting thing to include?
    - Like emphasis on establishment?
    - Tranformation: arc-sine or log? Counts or proportions? ANOVAs are on arc-sine proportions, but models are based on counts. If counts are used, then 'survival' doesn't make sense, it the same number as 'establishment'. 
- Like exploratory figures and maps? Need anything else for pub?
- Soil sensor issue: Maple systematically off... See histogram
    - Exclude?
    - Legitimate way to correct? What did Winslow do?
    - Ignore?
_ What do do with missing data? Esp. for repeat measure data...
- Present current state of GLMMs: 
    - Big Q: Aggregate to site-level, or keep all frame data?
    - Currently using Poisson log-link on counts. Should I use binomial logit on proportions? Note inconsistency with ANOVA, and issue with survival (must be proprotion)
    - Gettting counter-intuitive signs on moisture coeffecient sometimes, when Maple is included.
    - Using 'dredge': an AIC-based exhaustive model selected constrained to 4 terms. Not foregoing ecological reasoning, just need a way to pick mois_q50 vs. mois_q75, for example. 
    - Preliminary results:  
        - Generally the GLMM results seem to support median soil moisture and maximum temperature
        - Species definitely important, but not neccessarily interaction.
- Present current state of repeat models
- GLMMs won't make great sense until Maple issue is resolved... 













