---
title: "Research Update"
author: "Tyler Hoecker"
date: "9/26/2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, error = FALSE)
library(tidyverse)
library(lubridate)
```

```{r, include = F}
this_version <- 'data/seed_addition_2018_running_update.csv'

seedlings <- read_csv(this_version) %>% 
  select(-starts_with('height_header'),-starts_with('basal_header'), 
         -ends_with('_note'), -`_id`,-`_uuid`,-`_submission_time`,-`_index`) %>% 
  gather(cell, value, -date,-Fire,-Aspect,-Species,-Direction,-frameID,-Notes) %>% 
  separate(cell, into = c('variable','y_cell','x_cell'), sep = '_') %>%
  unite(x_cell, y_cell, col = 'cell') %>% 
  filter(Species != 'control_pico', Species != 'control', 
         !is.na(value),
         value > 0) %>% 
  modify_at('date', as.POSIXct) %>% 
  mutate(Fire = recode(Fire, 'berry_glade'='Berry-Glade','berry_huck'='Berry-Huck', 'buffalo'='Buffalo', 'maple'='Maple')) %>%
  rename(aspect = Aspect,
         species = Species,
         site = Fire,
         rep = Direction) 

# Summarize counts
counts <- seedlings %>% 
  filter(variable == 'height') %>% 
  group_by(date, site, species, aspect) %>%
  summarize(count = n(),
            prop = n()/(5*50))

# Summarize measurements
meas_summ <- seedlings %>% 
  group_by(date, site, species, aspect, variable) %>% 
  summarize(med = quantile(value, 0.50, na.rm = T),
            lower = quantile(value, 0.05, na.rm = T),
            upper = quantile(value, 0.95, na.rm = T))
```

```{r, include=F}
source('code/read_soil_data.R')

soil_data <- soil_df %>% 
  mutate(value = if_else(variable == 'mois', value * 100, value)) %>% 
  group_by(site, aspect, date = floor_date(time, 'day'), variable) %>%
  summarise_at('value', c('min','mean','max')) 
```

```{r, include=F}
source('code/read_atmos_data.R') #creats 'atmos_df'

atmos_data <- atmos_df %>% 
  gather(variable, value, -site,-aspect,-time) %>%
  group_by(site, aspect, date = floor_date(time, 'day'), variable) %>% 
  summarise_at('value', c('min','mean','max'))
```

```{r echo = FALSE, fig.dim = c(12, 10)}
colVals <- c('flat' = '#009E73','north' = '#0072B2','south' = '#E69F00')
legLabs <- c('Flat','North','South')

# Counts, through time 
seedlings_time <- 
  ggplot(counts) +
  geom_line(aes(x = date, y = count*0.4, color = aspect), size = 1.5) +
  facet_wrap(~species+site, scales = 'free_y', ncol = 4) +
  #scale_y_continuous(sec.axis = sec_axis(~.*0.4, name = "Percent of planted")) +
  scale_x_datetime(limits = as.POSIXct(c("2018-06-15 00:00:00", "2018-08-15 00:00:00"))) +
  scale_color_manual(values = colVals, name = 'aspect') +
  labs(x = 'Date', y = 'Percent alive of planted\nPSME     PICO') +  
  theme_bw(base_size = 14) +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

# Abiotic through time
colVals2 <- c('Flat' = '#009E73','North' = '#0072B2','South' = '#E69F00')

atmos_time <- 
  ggplot(filter(atmos_data, site != "Berry-Grrizz", variable == 'air_temp')) +
  geom_ribbon(aes(x = date, ymin = min, ymax = max, fill = aspect), alpha = 0.6) +
  geom_line(aes(x = date, y = mean, color = aspect), size = 1) +
  facet_wrap(~site, ncol = 4) +
  scale_x_datetime(limits = as.POSIXct(c("2018-06-15", "2018-08-15"))) +
  scale_color_manual(values = colVals2) +
  scale_fill_manual(values = colVals2) +
  labs(x = 'Day', y = bquote(atop('Daily mean','air temp. ('*~degree*C*')'))) +
  theme_bw(base_size = 14) + 
  theme(strip.background = element_blank(),
    strip.text.x = element_text(face = 'bold'),
    axis.title.x = element_blank(),
    axis.text.x = element_blank())

soil_time <- 
  ggplot(soil_data) +
  geom_ribbon(aes(x = date, ymin = min, ymax = max, fill = aspect), alpha = 0.6) +
  geom_line(aes(x = date, y = mean, color = aspect), size = 1) +
  facet_wrap(~variable+site, ncol = 4) +
  scale_x_datetime(limits = as.POSIXct(c("2018-06-15", "2018-08-15"))) +
  scale_color_manual(values = colVals2) +
  scale_fill_manual(values = colVals2) +
  labs(x = 'Day', y = bquote(atop('Daily mean and range','mois./temp. ('*mu*'m'*~m^2*','*~degree*C*')'))) + 
  theme_bw(base_size = 14) + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())


cowplot::plot_grid(atmos_time, soil_time, seedlings_time, 
                     rel_heights = c(0.5,1,1), nrow = 3, align = 'v')
```


```{r, echo = FALSE, fig.dim = c(10,8)}
prop_alive <- seedlings %>% 
  filter(variable == 'height') %>% 
  group_by(date, site, species, aspect, frameID) %>%
  summarize(count = n(),
            prop = n()/(50))

ggplot(prop_alive) +
  geom_line(aes(x = date, y = prop, color = aspect, group = date), size = 1, alpha = 0.5) +
  geom_point(aes(x = date, y = prop, color = aspect), size = 5, alpha = 0.5) +
  facet_wrap(~species+site, ncol = 4, scales = 'free_y') +
  scale_color_manual(values = colVals, name = 'aspect') +
  theme_bw(base_size = 14) +
  labs(x = 'Measurement date', y = 'Proportion alive of planted')
```


### Abiotic analysis
```{r, echo = FALSE, fig.dim = c(10,4)}
abiotic_df <- full_join(soil_data, atmos_data) 

air_soil_diff <- abiotic_df %>% 
  filter(variable %in% c('temp','air_temp')) %>%
  select(-min, -max) %>% 
  spread(variable, mean) %>% 
  mutate(diff = temp - air_temp) %>% 
  filter(!is.na(diff))


ggplot(air_soil_diff) +
  geom_line(aes(x = date, y = diff, color = aspect), size = 1) +
  facet_wrap(~site, ncol = 4) +
  scale_color_manual(values = colVals2, name = 'aspect') +
  labs(x = 'Date', y = 'Soil temp. - air temp.')+
  theme_bw(base_size = 14)
```


```{r, echo = FALSE, fig.dim = c(12,12)}
abiotic_df_sel <- abiotic_df %>% 
  filter(variable %in% c("mois","temp","air_temp","atms_press","rel_hum"),
         aspect != 'Old')

ggplot(abiotic_df_sel, aes(x = date, y = mean)) +
  geom_ribbon(aes(x = date, ymin = min, ymax = max, fill = aspect), alpha = 0.6) +
  geom_line(aes(color = aspect)) +
  scale_color_manual(values = colVals2) +
  scale_fill_manual(values = colVals2) +
  scale_x_datetime(limits = as.POSIXct(c("2018-06-15 00:00:00", "2018-08-15 00:00:00"))) +
  facet_wrap(~variable+site, scales = 'free_y', ncol = 4) 
```


## Next steps
+ Use allomteric model to calculate relative growth rate. Will "detrend" growth and may reveal variation by aspect that is not clear now.
+ 

